<?php
/**
 * @copyright 2015 City of Bloomington, Indiana
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 * @param string $google_calendar_id
 */
?>
<dl><dt><label  for="google_calendar_id"><?= $this->_('google_calendar_id'); ?></label></dt>
    <dd><input name="google_calendar_id" id="google_calendar_id" value="<?= $google_calendar_id; ?>" /></dd>
</dl>
